import Head from 'next/head';
import styles from '../styles/Home.module.css';
import { notion } from '../lib/notionBlocks';
import { RenderBlocks } from '../lib/notionBlocks/render';
import { Block, PageProperties } from '../lib/notionBlocks/types';
import { Meta } from '../components/Meta';
import Main from '../components/Main';

interface HomeProps {
  pageProperties: PageProperties;
  pageBlocks: Block[];
}

const Home = ({ pageProperties, pageBlocks }: HomeProps) => {
  const title = pageProperties.properties.title?.title?.[0]?.plain_text;
  const Headers = (
    <Meta
      title="Borja"
      description="Next js Boilerplate is the perfect starter code for your project. Build your React application with the Next.js framework."
    />
  );

  return (
    <Main meta={Headers}>
      <div className={styles.container}>
        <Head>
          <title>{title}</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <main className={styles.main}>
          <h1 className={styles.title}>{title}</h1>
          <RenderBlocks blocks={pageBlocks} />
        </main>
      </div>
    </Main>
  );
};

export async function getStaticProps() {
  const url = 'Front-End-Development-56c48726a7ee40918bb6359576452f49';
  const pageId = notion.getPageId(url);
  const pageProperties = await notion.getPageProperties(pageId);
  const pageBlocks = await notion.getPageBlocks(pageId);
  const parsedBlocks = await notion.populateBlockData(pageBlocks.results as Block[]);

  return {
    props: {
      pageProperties,
      pageBlocks: parsedBlocks,
    },
  };
}

export default Home;
