name: daily-cron
on:
  schedule:
    - cron: '0 0 * * *'
jobs:
  cron:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger vercel build webhook
        run: |
          curl -X POST https://api.vercel.com/v1/integrations/deploy/prj_HH3aOLe2m5S3LJP0iDbXE7TcpeMz/qfGnyayfl7
